### PR TITLE
Feature 9 release

### PR DESCRIPTION
**Pull request by jprestop**
## Expected Differences ##

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

Reviewed changes with addition of NSF NCAR on the following pages based on the [Sundog guidance](https://sundog.ucar.edu/page/7480#Interim-Guidance-on--11):
- https://fasteddy-model.readthedocs.io/en/feature_9_release/index.html
- https://fasteddy-model.readthedocs.io/en/feature_9_release/Tutorial/getting_started.html

Reviewed the release notes:
- https://fasteddy-model.readthedocs.io/en/feature_9_release/release_notes.html

Reviewed the zenodo additions:
- https://fasteddy-model.readthedocs.io/en/feature_9_release/Tutorial/cases.html
- https://fasteddy-model.readthedocs.io/en/feature_9_release/Tutorial/cases/MBL.html

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Please review the new menu structure with the addition of the Release Notes and review the Release Notes themselves.  I welcome any suggestions for modifications.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [x] Do these changes include sufficient testing updates? **[N/A]**

- [x] Will this PR result in changes to the test suite? **[N/A]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by **[20240422]**.</br>

## Pull Request Checklist ##
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Select: **Reviewer(s)**
- [x] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by jsauer-NCAR** [comment]
Could we please adjust the last paragraph of the Release notes intro text to read as 
`In addition to the initial code, this release includes a patch for building the system in the current NSF NCAR high performance computing environment on the Casper and Derecho platforms, along with other changes as detailed below:`

**Review by jsauer-NCAR — CHANGES_REQUESTED** [review]
I made the following comment in the PR regarding an adjustment to the release notes text already. Could we please adjust the last paragraph of the Release notes intro text to read as
`In addition to the initial code, this release includes a patch for building the system in the current NSF NCAR high performance computing environment on the Casper and Derecho platforms, along with other changes as detailed below:`

Also in the tutorial cases.rst I don't think the URL 'https://github.com/NCAR/FastEddy-model/tutorials' will work.  I tried that link and it didn't work for me. I also tried to navigate via browser to https://github.com/NCAR/FastEddy-model/SRC just in case it was a matter of the folder existing in the main branch, that didn't work either.  I'd suggest we simply change the text to read `in the tutorials directory of the https://github.com/NCAR/FastEddy-model `.

Finally I notice the phrase 'no-title' at the top of the RTD page for the cases (see attached image). Will this get a version number or something automatically or is an adjustment to the .rst needed?
Screen Shot 2024-04-19 at 7 29 19 AM

Once these points are addressed, it is all set.

**Comment by jprestop** [comment]
Hi @jsauer-NCAR. Thank you for your attention to detail.  I'm so glad you caught these problems that I missed!  I pushed the release date forward to **Monday** to give you more time to review and to give me more time to focus on the release next week.

1. I have changed the language to be as you indicated. Thank you for your work on rephrasing that text.
> In addition to the initial code, this release includes a patch for building the system in the current NSF NCAR high performance computing environment on the Casper and Derecho platforms, along with other changes as detailed below:

2. Great catch on the link `https://github.com/NCAR/FastEddy-model/tutorials` not working.  Navigating to that page in the repo it looks like it should actually be `https://github.com/NCAR/FastEddy-model/tree/main/tutorials`, however, I like your suggested change better anyway.  However, I did make one adjustment, which is instead of listing the link itself, I specified the text in the following way (also modifying the Zenodo reference as well).
> Required tutorial resources including python utilities and Jupyter Notebooks are provided in the tutorials directory of the [FastEddy-model GitHub repository](https://github.com/NCAR/FastEddy-model) with required data for the moist dynamics example available at this [Zenodo record](https://zenodo.org/records/10982246).

I thought it looked more professional to have the text instead of the link, but please let me know if you do not prefer it and/or would like me to change the wording.

3.  Great catch on the 'no-title' reference and thank you for the screenshot, which was very helpful.  It looks like in order to fix that I needed to change the menu and get rid of the nice 'TUTORIAL' caption or have redundancy and list a "Tutorial" menu underneath the 'TUTORIAL' caption.  I was going to replace the 'TUTORIAL' caption with something else, but I couldn't really come up with anything worthwhile, so I just removed it.  Please be sure to take a look at the menu and navigate through to make sure it looks ok to you.

I'll request a re-review through GitHub and will plan to get back to this on **Monday** after you've had a chance to look it over and suggest any other changes.  Again, many thanks for your careful attention to ensuring everything is in good shape.

**Review by jsauer-NCAR — APPROVED** [review]

**Comment by jsauer-NCAR** [comment]
@jprestop Thanks for the adjustments and I like the use of text with hyperlink rather than URL in the documentation.  I went ahead and added the same formatting to the Zenodo record in the MBL.rst. via branch commit to feature_9_release.  PR with changes approved.

**Pull request merged**
